#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 /path/to/jdk-21-xxx.(tar.gz|tgz|zip)"
  exit 1
fi

ARCHIVE="$1"

if [[ ! -f "$ARCHIVE" ]]; then
  echo "ERROR: Archive not found: $ARCHIVE"
  exit 1
fi

# Folder this script lives in = install dir
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$BASE_DIR"

echo "Install dir: $BASE_DIR"
echo "Using archive: $ARCHIVE"

# Extract depending on extension
case "$ARCHIVE" in
  *.tar.gz|*.tgz)
    echo "Extracting tar.gz..."
    tar -xzf "$ARCHIVE" -C "$BASE_DIR"
    ;;
  *.zip)
    echo "Extracting zip..."
    unzip -q "$ARCHIVE" -d "$BASE_DIR"
    ;;
  *)
    echo "ERROR: Unsupported archive type. Use .tar.gz, .tgz, or .zip"
    exit 1
    ;;
esac

# Prefer jdk-21*; fallback to any jdk-*
JDK_DIR=$(find "$BASE_DIR" -maxdepth 1 -type d -name 'jdk-21*' | sort | tail -n 1 || true)
if [[ -z "$JDK_DIR" ]]; then
  JDK_DIR=$(find "$BASE_DIR" -maxdepth 1 -type d -name 'jdk-*' | sort | tail -n 1 || true)
fi

if [[ -z "$JDK_DIR" ]]; then
  echo "ERROR: Could not find extracted jdk-* directory in $BASE_DIR"
  exit 1
fi

# macOS bundle vs plain JDK dir
if [[ -d "$JDK_DIR/Contents/Home" ]]; then
  JAVA_HOME_PATH="$JDK_DIR/Contents/Home"
else
  JAVA_HOME_PATH="$JDK_DIR"
fi

echo "Detected JAVA_HOME: $JAVA_HOME_PATH"

############################################
# 1) Helper for bash / zsh / Git Bash / WSL
############################################
cat > "$BASE_DIR/use-jv.sh" <<EOF
#!/usr/bin/env bash
export JAVA_HOME="$JAVA_HOME_PATH"
export PATH="\$JAVA_HOME/bin:\$PATH"
echo "JAVA_HOME set to: \$JAVA_HOME"
java -version
EOF

chmod +x "$BASE_DIR/use-jv.sh"

############################################
# 2) Helper for PowerShell (Windows)
############################################
cat > "$BASE_DIR/use-jv.ps1" <<EOF
# Auto-generated by setup-jv.sh
\$javaHome = "$JAVA_HOME_PATH" -replace '/', '\\'
\$env:JAVA_HOME = \$javaHome
\$env:Path = "\$javaHome\\bin;" + \$env:Path
Write-Output "JAVA_HOME set to: \$env:JAVA_HOME"
java -version
EOF

echo
echo "Created:"
echo "  $BASE_DIR/use-jv.sh   (bash/zsh/Git Bash/WSL)"
echo "  $BASE_DIR/use-jv.ps1  (PowerShell)"

echo
echo "To ACTIVATE Java 21 in this shell:"
echo "  Unix shells:   source $BASE_DIR/use-jv.sh"
echo "  PowerShell:    .\\use-jv.ps1"
