#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 /path/to/jdk-21-xxx.tar.gz"
  exit 1
fi

TARBALL="$1"

if [[ ! -f "$TARBALL" ]]; then
  echo "ERROR: Tarball not found: $TARBALL"
  exit 1
fi

# Folder this script lives in = install dir
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$BASE_DIR"

echo "Install dir: $BASE_DIR"
echo "Using tarball: $TARBALL"

# Extract JDK into install dir
tar -xzf "$TARBALL" -C "$BASE_DIR"

# Prefer jdk-21*; fallback to any jdk-*
JDK_DIR=$(find "$BASE_DIR" -maxdepth 1 -type d -name 'jdk-21*' | sort | tail -n 1 || true)
if [[ -z "$JDK_DIR" ]]; then
  JDK_DIR=$(find "$BASE_DIR" -maxdepth 1 -type d -name 'jdk-*' | sort | tail -n 1 || true)
fi

if [[ -z "$JDK_DIR" ]]; then
  echo "ERROR: Could not find extracted jdk-* directory in $BASE_DIR"
  exit 1
fi

# macOS bundle vs plain JDK dir
if [[ -d "$JDK_DIR/Contents/Home" ]]; then
  JAVA_HOME_PATH="$JDK_DIR/Contents/Home"
else
  JAVA_HOME_PATH="$JDK_DIR"
fi

echo "Detected JAVA_HOME: $JAVA_HOME_PATH"

############################################
# 1) Helper for bash / zsh / Git Bash / WSL
############################################
cat > "$BASE_DIR/use-jv.sh" <<EOF
#!/usr/bin/env bash
export JAVA_HOME="$JAVA_HOME_PATH"
export PATH="\$JAVA_HOME/bin:\$PATH"
echo "JAVA_HOME set to: \$JAVA_HOME"
java -version
EOF

chmod +x "$BASE_DIR/use-jv.sh"

############################################
# 2) Helper for PowerShell (Windows)
############################################
cat > "$BASE_DIR/use-jv.ps1" <<EOF
# Auto-generated by setup-jv.sh
\$javaHome = "$JAVA_HOME_PATH" -replace '/', '\\'
\$env:JAVA_HOME = \$javaHome
\$env:Path = "\$javaHome\\bin;" + \$env:Path
Write-Output "JAVA_HOME set to: \$env:JAVA_HOME"
java -version
EOF

echo
echo "Created:"
echo "  $BASE_DIR/use-jv.sh   (bash/zsh/Git Bash/WSL)"
echo "  $BASE_DIR/use-jv.ps1  (PowerShell)"

OS_NAME="\$(uname -s 2>/dev/null || echo Unknown)"
echo
echo "To ACTIVATE Java 21 in this shell:"
case "\$OS_NAME" in
  Darwin|Linux*)
    echo "  source $BASE_DIR/use-jv.sh"
    ;;
  MINGW*|MSYS*|CYGWIN*)
    echo "  In PowerShell: .\\use-jv.ps1"
    echo "  In Git Bash:   source use-jv.sh"
    ;;
  *)
    echo "  Unix shells:   source use-jv.sh"
    echo "  PowerShell:    .\\use-jv.ps1"
    ;;
esac
